"""empty message

Revision ID: 117dedc8c43b
Revises: 6f15cafd4711
Create Date: 2022-08-12 15:57:18.587759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '117dedc8c43b'
down_revision = '6f15cafd4711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.alter_column('shows', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('venue', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'date_created')
    op.alter_column('shows', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('artist', 'date_created')
    # ### end Alembic commands ###
