"""empty message

Revision ID: f8d6608b4d36
Revises: 5d426827ad92
Create Date: 2022-08-12 21:30:32.328730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d6608b4d36'
down_revision = '5d426827ad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_column('artist', 'website_link')
    op.add_column('venue', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'website')
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
